//chamar a rota de autenticar da api e pegar uma chave valida nova 

const apiKey =
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTI0NzcxNC0zZjdiLTRkMjAtYmUzMy03MGI2OWFkNDM3NjIiLCJlbWFpbCI6ImNhbWlsZWNvZWxobzIzQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJDYW1pbGUiLCJuYmYiOjE2OTcwNTIwMTUsImV4cCI6MTY5NzA4MDgxNSwiaWF0IjoxNjk3MDUyMDE1LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.GPc87R-R_R3qoxcsOvKj6AgSdE05ZRglsMKuhSNRtNU';
