export const environment = {
  production: false,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTI0NzcxNC0zZjdiLTRkMjAtYmUzMy03MGI2OWFkNDM3NjIiLCJlbWFpbCI6ImNhbWlsZWNvZWxobzIzQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJDYW1pbGUiLCJuYmYiOjE2OTcyMTUxNjgsImV4cCI6MTY5NzI0Mzk2OCwiaWF0IjoxNjk3MjE1MTY4LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.NlxZNoHdV9i_uOLw_VPPHuOjRqlaeLNQ9os0y6p7_oM',
};
